### ISSUE TITLE
Why you use 'var'? 

### ISSUE THREAD

**Issue by dipiash** [UnSstrennen/cookie.js#2]
https://github.com/UnSstrennen/cookie.js/blob/13a2c04a951e28f5ee7be79fe57bbf161d789846/src/cookie.js#L12

1. Why you use `var` in code if you use `let`/`const`?
2. What about browsers support and min version of browsers in which library working? It might be helpfull to explain in readme.

**Comment by vanodevium** [comment]
Library uses let and const so Internet Explorer is unsupported

You can see supported browsers [here](https://caniuse.com/#feat=let)

**Comment by UnSstrennen** [comment]
Thanks for issue & pull request, gonna be fixed soon
